version: '3'

services: 

  db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes: 
        - ./mysql:/var/lib/mysql
      environment: 
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
      networks: 
        - node-network   

  app:
      container_name: app
      build: 
        context: ./express
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
      command: yarn start
      networks: 
        - node-network     
      tty: true
      ports: 
        - "3333:3333"
      depends_on: 
        - db

  nginx:
    container_name: nginx
    build: 
      context: ./nginx              
    networks: 
      - node-network  
    tty: true
    ports: 
      - "8080:80"
    depends_on:
      - app  

networks: 
  node-network:
    driver: bridge  
